services:
   bot:
      build: .
      container_name: chat-discord-bot
      restart: unless-stopped
      env_file:
         - .env
      environment:
         - NODE_ENV=development
         - DEBUG=*
      volumes:
         - .:/usr/src/chat-discord-bot
         - /usr/src/chat-discord-bot/node_modules
         - /usr/src/chat-discord-bot/dist
      tty: true
      stdin_open: true
      command: node --trace-warnings dist/index.js
